server:
  port: 8763

spring:
  application:
    name: discovery-service
  cloud:
    config:
      uri: http://j9c207.p.ssafy.io:8888/
      nane: keeping

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      enable-self-preservation: false
    service-url:
      defaultZone: http://j9c207.p.ssafy.io:${server.port}/eureka/
    instance:
      lease-renewal-interval-in-seconds: 1 # 디스커버리한테 1초마다 하트비트 전송  (기본 30초)
      lease-expiration-duration-in-seconds: 2 # 디스커버리는 서비스 등록 해제 하기 전에 마지막 하트비트에서부터 2초 기다림