# server port
server:
  port: 0

---
# logging
logging:
  level:
    org.hibernate: debug
    com.keeping.openaiservice: debug

---
# MSA setting
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://j9c207.p.ssafy.io:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#spring default setting
spring:
  application:
    name: openai-service
  rabbitmq:
    # host: 127.0.0.1
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, metrics, prometheus, busrefresh



