# server port
server:
  port: 0

---
# logging
logging:
  level:
    org.hibernate: debug
    com.keeping.missionservice: debug

---
# MSA setting
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#spring default setting
spring:
  application:
    name: mission-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, metrics, prometheus, busrefresh
        
fcm:
  file:
    name: keeping-95186-firebase-adminsdk-9r919-da255b2f4e.json