// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZKyforErCv__uO5ciDG77_TdxUIuwRm0',
    appId: '1:926429802747:web:ae59a55c1c7d900790805e',
    messagingSenderId: '926429802747',
    projectId: 'keeping-dc42f',
    authDomain: 'keeping-dc42f.firebaseapp.com',
    storageBucket: 'keeping-dc42f.appspot.com',
    measurementId: 'G-Y6E42LVHPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWmD28vXwr8HQcIQmjrW_fZMTVq8a2SNo',
    appId: '1:926429802747:android:1c00de6777c5e72f90805e',
    messagingSenderId: '926429802747',
    projectId: 'keeping-dc42f',
    storageBucket: 'keeping-dc42f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxACUuO5soe79H5XFJwf_3co_0YcRxpac',
    appId: '1:926429802747:ios:92cf3c052a57af4a90805e',
    messagingSenderId: '926429802747',
    projectId: 'keeping-dc42f',
    storageBucket: 'keeping-dc42f.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxACUuO5soe79H5XFJwf_3co_0YcRxpac',
    appId: '1:926429802747:ios:9c2de841ce7b8f0a90805e',
    messagingSenderId: '926429802747',
    projectId: 'keeping-dc42f',
    storageBucket: 'keeping-dc42f.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
